# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# TRMM_upsample.py
# Created on: 2016-06-23 10:55:14.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

#Make a separate raster *.img file for each dimension value (time) in a netcdf file  
  
import arcpy, os, time, datetime, calendar  
from arcpy import env  
from arcpy.sa import *  
  
# Input data source  
  
#########Change folder  
arcpy.env.workspace = "E:\DEVELOP\CostaRica_SPI_062416" # Change folder++  
#########  
  
arcpy.env.overwriteOutput = True  
arcpy.env.scratchWorkspace = "E:\DEVELOP\CostaRica_SPI_062416"  
  
# Loop through a list of files in the workspace  
SPIfiles = arcpy.ListFiles("*.txt")  
  
for filename in SPIfiles:  
    print("Processing: " + filename)  
          
    # Set local variables  
    inASCII = arcpy.env.workspace + "/" + filename  
 
#########Change folder      
    outRasterFolder = "E:\DEVELOP\TRMM_PR_point25raster"  
#########  

    outRaster = outRasterFolder + "/" + filename +"_SPI" + ".tif"
    outRaster1= filename +".tif"
  
    # Execute ASCII to Raster  
    arcpy.ASCIIToRaster_conversion(inASCII,outRaster1, "FLOAT")  
    #print "Created Raster Layer for " + a

    # Process: Copy Raster
    arcpy.CopyRaster_management(outRaster1, outRaster, "", "", "-3.402823e+038", "NONE", "NONE", "", "NONE", "NONE")

    print "Created Raster for SPI "  + filename
    

              
print "\nEnd of processing ... YAHOO!!!"  