# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# TRMM_upsample.py
# Created on: 2016-06-23 10:55:14.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

#Make a separate raster *.img file for each dimension value (time) in a netcdf file  
  
import arcpy, os, time, datetime, calendar  
from arcpy import env  
from arcpy.sa import *  
  
# Input data source  
  
#########Change folder  
arcpy.env.workspace = "E:\DEVELOP\TRMM_PR_cdfs" # Change folder++  
#########  
  
arcpy.env.overwriteOutput = True  
arcpy.env.scratchWorkspace = "E:\DEVELOP\TRMM_PR_cdfs"  
  
# Loop through a list of files in the workspace  
NetCDFfiles = arcpy.ListFiles("*.nc")  
  
for filename in NetCDFfiles:  
    print("Processing: " + filename)  
          
    # Set local variables  
    inNetCDF = arcpy.env.workspace + "/" + filename  
  
#########Change the variable  
    variable = "pcp"   
#########  
      
    XDimension = "longitude"  
    YDimension = "latitude"  
    bandDimension = ""  
    dimensionValues = ""  
    valueSelectionMethod = "BY_VALUE"  
  
#########Change the variable ###  
    InMemory_netcdf_raster = "pcp"   
#########  
      
#########Change folder      
    outRasterFolder = "E:\DEVELOP\TRMM_PR_point25raster"  
#########  

    print('Run Succesful part 1')

    outTIFF = outRasterFolder + "/" + filename +"point25raster" + ".tif"  
  
    # Execute MakeNetCDFRasterLayer  
    arcpy.MakeNetCDFRasterLayer_md(inNetCDF, variable, XDimension, YDimension, InMemory_netcdf_raster, bandDimension, dimensionValues, valueSelectionMethod)  
    #print "Created NetCDF Layer for " + a  
              
    # Process: Copy Raster  
    arcpy.CopyRaster_management(InMemory_netcdf_raster, outTIFF, "", "", "", "NONE", "NONE", "")
    print "Created Raster for point25raster "  + filename 
              
print "\nEnd of processing ... YAHOO!!!"  




