# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Created on: 2016-06-23 10:55:14.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

#Make a separate raster *.img file for each dimension value (time) in a netcdf file  
  
import arcpy, os, time, datetime, calendar  
from arcpy import env  
from arcpy.sa import *  
  
# Input data source  
  
#########Change folder  
arcpy.env.workspace = "E:\DEVELOP\TRMM_PR_point1raster" # Change folder++  
#########
  
arcpy.env.overwriteOutput = True  
arcpy.env.scratchWorkspace = "\\Mac\Home\Documents\ArcGIS\Default.gdb"


# Loop through a list of files in the workspace  
Rasterpoint1files = arcpy.ListFiles("*point1raster.tif")

outASCIIFolder = "E:\DEVELOP\TRMM_PR_point1_ASCII/" 

for filename in Rasterpoint1files:  
    print("Processing: " + filename)
 # Set local variables  
    inRaster = arcpy.env.workspace + "/" + filename
    outName =  filename[0:15] + "point1ASCII" + ".txt" 

    outFile = outASCIIFolder + outName 

    # Process:Raster to ASCII
    arcpy.RasterToASCII_conversion(inRaster, outFile)
   
    print "Created ASCII for point1raster "  + filename 







