# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Created on: 2016-06-23 10:55:14.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

#Make a separate raster *.img file for each dimension value (time) in a netcdf file  
  
import arcpy, os, time, datetime, calendar  
from arcpy import env  
from arcpy.sa import *  
  
# Input data source  
  
#########Change folder  
arcpy.env.workspace = "E:\DEVELOP\TRMM_PR_point1raster" # Change folder++  
#########
  
arcpy.env.overwriteOutput = True  
arcpy.env.scratchWorkspace = "\\Mac\Home\Documents\ArcGIS\Default.gdb"


# Loop through a list of files in the workspace  
Rasterpoint1files = arcpy.ListFiles("*point1raster.tif")

outnetCDFFolder = "E:\DEVELOP\CostaRica_Mothly_PCP_netCDF/" 

for filename in Rasterpoint1files:  
    print("Processing: " + filename)
    # Set local variables  
    #inRaster = arcpy.env.workspace + "/" + filename
    outName =  filename[5:9] + "." +filename[9:11] + ".cd" 

    outFile = outnetCDFFolder + outName 

    # Process:Raster to ASCII
    arcpy.RasterToNetCDF_md(+filename, outFile, "filename", "", "lon", "lat", "", "")
    #arcpy.RasterToNetCDF_md(v3B43_20000101_7point1raster_tif, c20000101_nc, "3B43.20000101.7point1raster.tif", "", "lon", "lat", "", "")

    print "Created ASCII for point1raster "  + filename 












