# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# TRMM_upsample.py
# Created on: 2016-06-23 10:55:14.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

#Make a separate raster *.img file for each dimension value (time) in a netcdf file  
  
import arcpy, os, time, datetime, calendar  
from arcpy import env  
from arcpy.sa import *  
  
# Input data source  
  
#########Change folder  
arcpy.env.workspace = "E:\DEVELOP\TRMM_PR_point25raster" # Change folder++  
#########
  
arcpy.env.overwriteOutput = True  
arcpy.env.scratchWorkspace = "\\Mac\Home\Documents\ArcGIS\Default.gdb"  


# Loop through a list of files in the workspace  
Rasterpoint25files = arcpy.ListFiles("*ncpoint25raster.tif")

outRasterFolder = "E:\DEVELOP\TRMM_PR_point1raster_062416/" 
  
for filename in Rasterpoint25files:  
    print("Processing: " + filename)

    # Set local variables  
    inRaster = arcpy.env.workspace + "/" + filename
    outName =  filename[0:15] + "point1raster" + ".tif" 

    outRaster = outRasterFolder + outName 


    # Process: Resample
    arcpy.Resample_management(inRaster, outName, ".1 .1", "CUBIC")

    # Process: Copy Raster  
    arcpy.CopyRaster_management(outName, outRaster, "", "", "", "NONE", "NONE", "")
    print "Created Raster for point25raster "  + filename 

print "Created Raster for point1raster "  + filename




